.TH Streamcatcher 6 "14 September 2025" "0.0.0.1"
.SH NAME
streamcatcher \- Galaxis community app
.SH SYNOPSIS
.SY streamcatcher
.OP \-\-help
.OP \-\-version
.YS
.SH DESCRIPTION
.B streamcatcher
makes it possible to reward members who watch the stream
.SH OPTIONS
.TP
.BR \-\-help
Print a help message and exit.
.TP
.BR \-\-version
Display version information.
.SH EXIT STATUS
.B streamcatcher
always exits with status 0.
.SH COPYRIGHT
Copyright (c) 2025 Andras Kristof. This program is distributed under the MIT
license. See the file
.I LICENSE
distributed with this program for details.
